#!/usr/bin/env python3
"""
Stage 34 — Build the paper through the texflow MCP (IEEE conference class).

Reads paper/GridPowerAgent_IEEE_Conference.tex (generated by 31), converts to
texflow structured blocks, inserts them via the MCP stdio server into
workspace-gridpower, adds the verified bibliography, and renders.

Conversions:
  - \\ref/\\eqref  -> hard textual numbers (insertion order == numbering order)
  - \\cite         -> [n] via the compiled .bbl order
  - \\textbf/\\emph/\\texttt -> **x*/ *x* / `x`
  - tables stay as RawLatex (booktabs + scriptsize notes preserved verbatim)
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, "/home/touhid/Documents/llmpaper")
from importlib import import_module
t33 = import_module("33_texflow_driver") if "33_texflow_driver" in sys.modules else None
# import driver without running its __main__
spec_ns = {}
exec(compile(open("/home/touhid/Documents/llmpaper/33_texflow_driver.py").read()
             .split('if __name__')[0], "33_texflow_driver.py", "exec"), spec_ns)
Tx = spec_ns["Tx"]

ROOT = Path("/home/touhid/Documents/llmpaper")
WS = "/home/touhid/Documents/texflowmcp/workspace-gridpower"
tex = (ROOT / "paper/GridPowerAgent_IEEE_Conference.tex").read_text()

# ---------- reference mappings ----------
# printed numbering = .bbl order (= order of first citation, IEEEtran.bst)
_bbl = (ROOT / "paper/GridPowerAgent_IEEE_Conference.bbl").read_text()
CITES = re.findall(r"\\bibitem\{([^}]*)\}", _bbl)

REFS = {
    "fig:methodology": "Fig. 1", "fig:scenarios": "Fig. 2", "fig:arch": "Fig. 3",
    "fig:diag": "Fig. 4", "fig:tools": "Fig. 5", "fig:halluc": "Fig. 6",
    "fig:generalization": "Fig. 7", "fig:tradeoff": "Fig. 8",
    "tab:corpus": "Table I", "tab:pilot": "Table II", "tab:results": "Table III",
    "tab:ni": "Table IV", "tab:perclass": "Table V", "tab:trace": "Table VI",
    "sec:proto": "Sec. VI", "sec:limits": "Sec. VIII", "sec:axis": "Sec. VII-C",
    "eq:meas": "(1)", "eq:wls": "(2)", "eq:wlsobj": "(3)", "eq:sev": "(4)",
}

def cite_repl(m):
    keys = [k.strip() for k in m.group(1).split(",")]
    nums = sorted(CITES.index(k) + 1 for k in keys if k in CITES)
    if len(nums) < len(keys):
        print(f"[WARN] uncited keys: {set(keys) - set(CITES)}")
    return "[" + ",".join(str(n) for n in nums) + "]"

def conv(s: str) -> str:
    s = s.replace("{,}", ",")
    s = s.replace("\\ ", " ")
    s = re.sub(r"~\\(ref|eqref)\{([^}]*)\}",
               lambda m: "~" + REFS.get(m.group(2), m.group(2)), s)
    s = re.sub(r"\\(ref|eqref)\{([^}]*)\}", lambda m: REFS.get(m.group(2), m.group(2)), s)
    s = re.sub(r"~\\cite\{([^}]*)\}", cite_repl, s)
    s = re.sub(r"\\cite\{([^}]*)\}", cite_repl, s)
    s = re.sub(r"\\textbf\{([^{}]*)\}", r"**\1**", s)
    s = re.sub(r"\\emph\{([^{}]*)\}", r"*\1*", s)
    s = re.sub(r"\\texttt\{([^{}]*)\}", r"`\1`", s)
    s = s.replace("\\%", "%").replace("\\_", "_").replace("\\&", "&")
    s = re.sub(r"\$\{\\sim\}([0-9.]+)\$", r"about \1", s)
    s = s.replace("${\\sim}", "~").replace("\\textasciitilde{}", "~")
    s = s.replace("\\,", " ").replace("\\;", " ")
    s = re.sub(r"(?<![\\$])~", " ", s)  # tie space, not inside math
    s = s.replace("\\,", " ")
    s = s.replace("\\quotes{}", '"')
    s = s.replace("``", '"').replace("''", '"')
    s = s.replace("\\S", "S")
    s = re.sub(r"`([^`]*)`", r"\1", s)  # code spans -> plain text (escape_LATex misses _ inside \texttt)
    s = s.replace("`grid_query`", "grid query")
    for pre in ["Table", "Fig.", "Sec.", "Eqs."]:
        s = s.replace(f"{pre} {pre}", pre)
    return s.strip()

def parse_bib():
    txt = (ROOT / "paper/references.bib").read_text()
    entries, cur = [], []
    for line in txt.splitlines():
        if line.startswith("@") and cur:
            entries.append("\n".join(cur)); cur = [line]
        elif line.startswith("@"):
            cur = [line]
        else:
            if cur:
                cur.append(line)
    if cur:
        entries.append("\n".join(cur))
    return [e for e in entries if e.strip()]

def parse_tex_blocks():
    body = tex.split("\\begin{document}")[1].split("\\maketitle")[1]
    abstract = re.search(r"\\begin{abstract}(.*?)\\end{abstract}", tex, re.DOTALL).group(1).strip()
    body = re.sub(r"\\begin{abstract}.*?\\end{abstract}", "", body, flags=re.DOTALL)
    body = body.split("\\bibliographystyle")[0]
    body = re.sub(r"\\label\{[^}]*\}", "", body)
    body = re.sub(r"\\begin\{IEEEkeywords\}.*?\\end\{IEEEkeywords\}", "", body, flags=re.DOTALL)
    body = re.sub(r"\\hypersetup\{[^}]*\}", "", body)
    blocks = []
    # tokenise on environments and sectioning
    pat = re.compile(
        r"(\\section\{[^}]*\})|(\\subsection\{[^}]*\})|"
        r"(\\begin\{figure\}.*?\\end\{figure\})|"
        r"(\\begin\{table\}.*?\\end\{table\})|"
        r"(\\begin\{equation\}.*?\\end\{equation\})", re.DOTALL)
    pos = 0
    para_buf = []

    def flush_para():
        while para_buf:
            blocks.append(("p", para_buf.pop(0)))

    for m in pat.finditer(body):
        text = body[pos:m.start()]
        for para in re.split(r"\n\s*\n", text):
            p = conv(para)
            if p:
                para_buf.append(p)
        flush_para()
        if m.group(1):
            flush_para()
            blocks.append(("section", conv(m.group(1)[len("\\section{"):-1])))
        elif m.group(2):
            flush_para()
            blocks.append(("subsection", conv(m.group(2)[len("\\subsection{"):-1])))
        elif m.group(3):
            env = m.group(0)
            path = re.search(r"\\includegraphics\[[^\]]*\]\{([^}]*)\}", env).group(1)
            cap = conv(re.search(r"\\caption\{((?:[^{}]|\{[^{}]*\})*)\}", env, re.DOTALL).group(1))
            cap = cap.replace("**", "").replace("*", "")
            blocks.append(("figure", path, cap))
        elif m.group(4):
            blocks.append(("rawtable", m.group(0)))
        elif m.group(5):
            eq = m.group(0)
            eq = re.sub(r"\\begin\{equation\}|\\end\{equation\}", "", eq)
            eq = re.sub(r"\\label\{[^}]*\}", "", eq).strip()
            blocks.append(("equation", eq))
        pos = m.end()
    for para in re.split(r"\n\s*\n", body[pos:]):
        p = conv(para)
        if p:
            para_buf.append(p)
    flush_para()
    return abstract, blocks

abstract, blocks = parse_tex_blocks()
print(f"parsed: abstract {len(abstract)} chars, {len(blocks)} blocks")

# sync figure assets into the workspace (texflow compiles in a temp dir)
import shutil
for fig_src in (ROOT / "paper/figures").glob("*.png"):
    shutil.copy2(fig_src, Path(WS) / "figures" / fig_src.name)

t = Tx(WS)
# reset any prior content and set metadata
t.call("document", {"action": "reset"})
t.call("document", {"action": "create", "document_class": "ieee-conference",
                    "title": "GridPowerAgent: A Grid-Aware LLM Agent for Power System Event Understanding and Tool-Orchestrated Decision Support",
                    "author": "Anonymous Authors",
                    "abstract": conv(abstract),
                    "keywords": ["power system operation", "large language models",
                                 "local inference", "retrieval-augmented generation",
                                 "synthetic benchmark", "state estimation"]})
t.call("document", {"action": "update", "title": "GridPowerAgent: A Grid-Aware LLM Agent for Power System Event Understanding and Tool-Orchestrated Decision Support"})

cur_section = None
count = {"section": 0, "p": 0, "figure": 0, "table": 0, "equation": 0, "raw": 0}
for b in blocks:
    kind = b[0]
    if kind == "section":
        t.call("edit", {"action": "insert", "block_type": "section", "title": b[1], "level": 1})
        cur_section = b[1]
        count["section"] += 1
    elif kind == "subsection":
        t.call("edit", {"action": "insert", "block_type": "section", "section": cur_section,
                        "title": b[1], "level": 2})
        count["section"] += 1
    elif kind == "p":
        t.call("edit", {"action": "insert", "block_type": "paragraph", "section": cur_section,
                        "content": b[1]})
        count["p"] += 1
    elif kind == "figure":
        t.call("edit", {"action": "insert", "block_type": "figure", "section": cur_section,
                        "path": b[1], "caption": b[2], "width": "0.72\\columnwidth"})
        count["figure"] += 1
    elif kind == "equation":
        t.call("edit", {"action": "insert", "block_type": "equation", "section": cur_section,
                        "content": b[1]})
        count["equation"] += 1
    elif kind == "rawtable":
        raw = re.sub(r"(\\begin\{tabular\}\{[^}]*\})",
                     r"\\noindent\\resizebox{\\columnwidth}{!}{%\n\1", b[1])
        raw = raw.replace("\\end{tabular}", "\\end{tabular}}")
        raw = re.sub(r"~?\\(ref|eqref)\{([^}]*)\}",
                     lambda m: REFS.get(m.group(2), "Sec. " + m.group(2).split(":")[-1].title()[:3]), raw)
        t.call("edit", {"action": "insert", "block_type": "raw", "section": cur_section,
                        "content": raw})
        count["raw"] += 1

print("inserted:", count)

# bibliography as raw thebibliography block (cites were inlined as [n]; bibtex
# would otherwise produce an empty .bbl and crash on \end{thebibliography})
bbl = (ROOT / "paper/GridPowerAgent_IEEE_Conference.bbl").read_text()
bbl = re.sub(r"\begin\{thebibliography\}\{[^}]*\}", r"\\begin{thebibliography}{}", bbl)
t.call("edit", {"action": "insert", "block_type": "raw", "section": "Acknowledgment" if False else cur_section,
                "content": bbl})
print("bib block inserted")

print(t.call("document", {"action": "outline"}))
t.close()
print("[PASS] texflow structure built")
